//! Tests for the store path encoding (RFC 005 D-1, RFC 013 D-1). The table is **generated by Mercurial's own
//! encoder** (`mercurial.store._hybridencode` and `_pathencode`, Mercurial 7.2.4, on the paths below) and
//! fixed here, so these tests need no Python; the live-store sweep re-checks against a real `hg` when present.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]

use std::path::PathBuf;
use std::process::Command;

use super::{StorePaths, store_paths};

/// (logical path, dotencode, index name, data name), each from `_hybridencode(b"data/" + path + ext, dotencode)`.
/// Includes the reserved names, `.i`/`.d`/`.hg` directories, trailing dots and spaces, uppercase, `_`, `~`,
/// non-ASCII, paths of 120 bytes and one more, many deep directories (the 68-byte cut), long basenames (the
/// filler), directory prefixes that end in `.` or a space after the 8-byte cut, and every one with
/// `dotencode` false.
const FROM_MERCURIAL: &[(&str, bool, &str, &str)] = &[
    ("a.txt", true, "data/a.txt.i", "data/a.txt.d"),
    ("a.txt", false, "data/a.txt.i", "data/a.txt.d"),
    (
        "nor-mal.txt",
        true,
        "data/nor-mal.txt.i",
        "data/nor-mal.txt.d",
    ),
    (
        "nor-mal.txt",
        false,
        "data/nor-mal.txt.i",
        "data/nor-mal.txt.d",
    ),
    (
        "Sub/File.TXT",
        true,
        "data/_sub/_file._t_x_t.i",
        "data/_sub/_file._t_x_t.d",
    ),
    (
        "Sub/File.TXT",
        false,
        "data/_sub/_file._t_x_t.i",
        "data/_sub/_file._t_x_t.d",
    ),
    (
        "_under.txt",
        true,
        "data/__under.txt.i",
        "data/__under.txt.d",
    ),
    (
        "_under.txt",
        false,
        "data/__under.txt.i",
        "data/__under.txt.d",
    ),
    (".hidden", true, "data/~2ehidden.i", "data/~2ehidden.d"),
    (".hidden", false, "data/.hidden.i", "data/.hidden.d"),
    (
        ".config/App.ini",
        true,
        "data/~2econfig/_app.ini.i",
        "data/~2econfig/_app.ini.d",
    ),
    (
        ".config/App.ini",
        false,
        "data/.config/_app.ini.i",
        "data/.config/_app.ini.d",
    ),
    (
        "MixedCase.md",
        true,
        "data/_mixed_case.md.i",
        "data/_mixed_case.md.d",
    ),
    (
        "MixedCase.md",
        false,
        "data/_mixed_case.md.i",
        "data/_mixed_case.md.d",
    ),
    ("aux/x", true, "data/au~78/x.i", "data/au~78/x.d"),
    ("aux/x", false, "data/au~78/x.i", "data/au~78/x.d"),
    ("con.txt", true, "data/co~6e.txt.i", "data/co~6e.txt.d"),
    ("con.txt", false, "data/co~6e.txt.i", "data/co~6e.txt.d"),
    ("com1", true, "data/co~6d1.i", "data/co~6d1.d"),
    ("com1", false, "data/co~6d1.i", "data/co~6d1.d"),
    ("dir.i/f", true, "data/dir.i.hg/f.i", "data/dir.i.hg/f.d"),
    ("dir.i/f", false, "data/dir.i.hg/f.i", "data/dir.i.hg/f.d"),
    (".hg/x", true, "data/~2ehg.hg/x.i", "data/~2ehg.hg/x.d"),
    (".hg/x", false, "data/.hg.hg/x.i", "data/.hg.hg/x.d"),
    ("a./b", true, "data/a~2e/b.i", "data/a~2e/b.d"),
    ("a./b", false, "data/a~2e/b.i", "data/a~2e/b.d"),
    ("a /b", true, "data/a~20/b.i", "data/a~20/b.d"),
    ("a /b", false, "data/a~20/b.i", "data/a~20/b.d"),
    ("Aux.txt", true, "data/_aux.txt.i", "data/_aux.txt.d"),
    ("Aux.txt", false, "data/_aux.txt.i", "data/_aux.txt.d"),
    ("auxx", true, "data/auxx.i", "data/auxx.d"),
    ("auxx", false, "data/auxx.i", "data/auxx.d"),
    ("nul", true, "data/nu~6c.i", "data/nu~6c.d"),
    ("nul", false, "data/nu~6c.i", "data/nu~6c.d"),
    ("lpt9.c", true, "data/lp~749.c.i", "data/lp~749.c.d"),
    ("lpt9.c", false, "data/lp~749.c.i", "data/lp~749.c.d"),
    ("x.", true, "data/x..i", "data/x..d"),
    ("x.", false, "data/x..i", "data/x..d"),
    ("x ", true, "data/x .i", "data/x .d"),
    ("x ", false, "data/x .i", "data/x .d"),
    ("aux", true, "data/au~78.i", "data/au~78.d"),
    ("aux", false, "data/au~78.i", "data/au~78.d"),
    ("prn.c", true, "data/pr~6e.c.i", "data/pr~6e.c.d"),
    ("prn.c", false, "data/pr~6e.c.i", "data/pr~6e.c.d"),
    ("com9.txt", true, "data/co~6d9.txt.i", "data/co~6d9.txt.d"),
    ("com9.txt", false, "data/co~6d9.txt.i", "data/co~6d9.txt.d"),
    ("lpt1", true, "data/lp~741.i", "data/lp~741.d"),
    ("lpt1", false, "data/lp~741.i", "data/lp~741.d"),
    ("com0", true, "data/com0.i", "data/com0.d"),
    ("com0", false, "data/com0.i", "data/com0.d"),
    ("com10", true, "data/com10.i", "data/com10.d"),
    ("com10", false, "data/com10.i", "data/com10.d"),
    ("conprn", true, "data/conprn.i", "data/conprn.d"),
    ("conprn", false, "data/conprn.i", "data/conprn.d"),
    ("foo.aux", true, "data/foo.aux.i", "data/foo.aux.d"),
    ("foo.aux", false, "data/foo.aux.i", "data/foo.aux.d"),
    ("dir.d/f", true, "data/dir.d.hg/f.i", "data/dir.d.hg/f.d"),
    ("dir.d/f", false, "data/dir.d.hg/f.i", "data/dir.d.hg/f.d"),
    ("z.hg/w", true, "data/z.hg.hg/w.i", "data/z.hg.hg/w.d"),
    ("z.hg/w", false, "data/z.hg.hg/w.i", "data/z.hg.hg/w.d"),
    ("q.i.hg/r", true, "data/q.i.hg.hg/r.i", "data/q.i.hg.hg/r.d"),
    (
        "q.i.hg/r",
        false,
        "data/q.i.hg.hg/r.i",
        "data/q.i.hg.hg/r.d",
    ),
    (
        "a.i/b.d/c.hg/d",
        true,
        "data/a.i.hg/b.d.hg/c.hg.hg/d.i",
        "data/a.i.hg/b.d.hg/c.hg.hg/d.d",
    ),
    (
        "a.i/b.d/c.hg/d",
        false,
        "data/a.i.hg/b.d.hg/c.hg.hg/d.i",
        "data/a.i.hg/b.d.hg/c.hg.hg/d.d",
    ),
    (
        "dir.i.hg/f",
        true,
        "data/dir.i.hg.hg/f.i",
        "data/dir.i.hg.hg/f.d",
    ),
    (
        "dir.i.hg/f",
        false,
        "data/dir.i.hg.hg/f.i",
        "data/dir.i.hg.hg/f.d",
    ),
    ("x.y.i/z", true, "data/x.y.i.hg/z.i", "data/x.y.i.hg/z.d"),
    ("x.y.i/z", false, "data/x.y.i.hg/z.i", "data/x.y.i.hg/z.d"),
    ("a b/c d", true, "data/a b/c d.i", "data/a b/c d.d"),
    ("a b/c d", false, "data/a b/c d.i", "data/a b/c d.d"),
    (
        "tab\u{9}name",
        true,
        "data/tab~09name.i",
        "data/tab~09name.d",
    ),
    (
        "tab\u{9}name",
        false,
        "data/tab~09name.i",
        "data/tab~09name.d",
    ),
    ("q:r", true, "data/q~3ar.i", "data/q~3ar.d"),
    ("q:r", false, "data/q~3ar.i", "data/q~3ar.d"),
    ("star*", true, "data/star~2a.i", "data/star~2a.d"),
    ("star*", false, "data/star~2a.i", "data/star~2a.d"),
    ("tilde~x", true, "data/tilde~7ex.i", "data/tilde~7ex.d"),
    ("tilde~x", false, "data/tilde~7ex.i", "data/tilde~7ex.d"),
    (
        "café.txt",
        true,
        "data/caf~c3~a9.txt.i",
        "data/caf~c3~a9.txt.d",
    ),
    (
        "café.txt",
        false,
        "data/caf~c3~a9.txt.i",
        "data/caf~c3~a9.txt.d",
    ),
    (
        "日本語/ファイル.txt",
        true,
        "data/~e6~97~a5~e6~9c~ac~e8~aa~9e/~e3~83~95~e3~82~a1~e3~82~a4~e3~83~ab.txt.i",
        "data/~e6~97~a5~e6~9c~ac~e8~aa~9e/~e3~83~95~e3~82~a1~e3~82~a4~e3~83~ab.txt.d",
    ),
    (
        "日本語/ファイル.txt",
        false,
        "data/~e6~97~a5~e6~9c~ac~e8~aa~9e/~e3~83~95~e3~82~a1~e3~82~a4~e3~83~ab.txt.i",
        "data/~e6~97~a5~e6~9c~ac~e8~aa~9e/~e3~83~95~e3~82~a1~e3~82~a4~e3~83~ab.txt.d",
    ),
    (
        "Upper/Case_Dir/Under_score.TXT",
        true,
        "data/_upper/_case___dir/_under__score._t_x_t.i",
        "data/_upper/_case___dir/_under__score._t_x_t.d",
    ),
    (
        "Upper/Case_Dir/Under_score.TXT",
        false,
        "data/_upper/_case___dir/_under__score._t_x_t.i",
        "data/_upper/_case___dir/_under__score._t_x_t.d",
    ),
    ("...", true, "data/~2e...i", "data/~2e...d"),
    ("...", false, "data/....i", "data/....d"),
    ("..a", true, "data/~2e.a.i", "data/~2e.a.d"),
    ("..a", false, "data/..a.i", "data/..a.d"),
    ("a..", true, "data/a...i", "data/a...d"),
    ("a..", false, "data/a...i", "data/a...d"),
    ("a. ", true, "data/a. .i", "data/a. .d"),
    ("a. ", false, "data/a. .i", "data/a. .d"),
    (" lead", true, "data/~20lead.i", "data/~20lead.d"),
    (" lead", false, "data/ lead.i", "data/ lead.d"),
    (
        "director/director/director/director/director/director/director/director/director/director/director/director/file.txt",
        true,
        "dh/director/director/director/director/director/director/director/file.txt.ie4fde853768195f3d8cd3233ae19fd18c577264d.i",
        "dh/director/director/director/director/director/director/director/file.txt.d80aadab1ca9a852e591e75beeed65f5d7de527d4.d",
    ),
    (
        "director/director/director/director/director/director/director/director/director/director/director/director/file.txt",
        false,
        "dh/director/director/director/director/director/director/director/file.txt.ie4fde853768195f3d8cd3233ae19fd18c577264d.i",
        "dh/director/director/director/director/director/director/director/file.txt.d80aadab1ca9a852e591e75beeed65f5d7de527d4.d",
    ),
    (
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt",
        true,
        "dh/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxccb88ec49d6ca3c58bec4da1df38c299322ac45d.i",
        "dh/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx74fe261076e4a29704b306e26759e6bb8fdfedf5.d",
    ),
    (
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt",
        false,
        "dh/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxccb88ec49d6ca3c58bec4da1df38c299322ac45d.i",
        "dh/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx74fe261076e4a29704b306e26759e6bb8fdfedf5.d",
    ),
    (
        "Long/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/Under_Score-Name.TXT",
        true,
        "dh/long/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/under_sca21e04d84ed87ff3b2159b591c43401464551fd.i",
        "dh/long/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/under_s613c5d5f911be5eb68f39f5c5a71c063ecbe2ad4.d",
    ),
    (
        "Long/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/CamelCaseDirectory/Under_Score-Name.TXT",
        false,
        "dh/long/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/under_sca21e04d84ed87ff3b2159b591c43401464551fd.i",
        "dh/long/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/camelcas/under_s613c5d5f911be5eb68f39f5c5a71c063ecbe2ad4.d",
    ),
    (
        "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/éééééééééééééééééééééééééééééé/f",
        true,
        "dh/~7e~7e~7/~c3~a9~c/f.i7a3f265e6e7ee6d679a635de12d1cefe87be9367.i",
        "dh/~7e~7e~7/~c3~a9~c/f.dfcc7cdefcf1635e748aca7f1007faf56e404d228.d",
    ),
    (
        "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/éééééééééééééééééééééééééééééé/f",
        false,
        "dh/~7e~7e~7/~c3~a9~c/f.i7a3f265e6e7ee6d679a635de12d1cefe87be9367.i",
        "dh/~7e~7e~7/~c3~a9~c/f.dfcc7cdefcf1635e748aca7f1007faf56e404d228.d",
    ),
    (
        "d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f",
        true,
        "data/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f.i",
        "data/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f.d",
    ),
    (
        "d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f",
        false,
        "data/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f.i",
        "data/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/d/f.d",
    ),
    (
        "abcdefg./mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
        true,
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm1b45299e84af22be97117b003c8efc017ed1efae.i",
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmf8f9c870dd57162d7a666d06bf348d180fda4606.d",
    ),
    (
        "abcdefg./mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
        false,
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm1b45299e84af22be97117b003c8efc017ed1efae.i",
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmf8f9c870dd57162d7a666d06bf348d180fda4606.d",
    ),
    (
        "abcdefg /mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
        true,
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmc2b517019feb01a077bb0f3718c88318d064a44a.i",
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmf2298ab7b12e8c0181569efa5778810aa884f3a3.d",
    ),
    (
        "abcdefg /mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
        false,
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmc2b517019feb01a077bb0f3718c88318d064a44a.i",
        "dh/abcdefg~/mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmf2298ab7b12e8c0181569efa5778810aa884f3a3.d",
    ),
    (
        "abcdefg.hij/klmnopq /nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "dh/abcdefg_/klmnopq~/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnd6ca0111cf53a94c20b7aec33d525f60ea11337f.i",
        "dh/abcdefg_/klmnopq~/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn1964c074671946578abd2e0c8e9326308aaea798.d",
    ),
    (
        "abcdefg.hij/klmnopq /nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "dh/abcdefg_/klmnopq~/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnd6ca0111cf53a94c20b7aec33d525f60ea11337f.i",
        "dh/abcdefg_/klmnopq~/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn1964c074671946578abd2e0c8e9326308aaea798.d",
    ),
    (
        "aux/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        true,
        "dh/au~78/ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc7b6090846cad996f7924750db24418e2c38642e6.i",
        "dh/au~78/ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2864171f95c048e9af1e52200b11f5148eba5899.d",
    ),
    (
        "aux/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        false,
        "dh/au~78/ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc7b6090846cad996f7924750db24418e2c38642e6.i",
        "dh/au~78/ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2864171f95c048e9af1e52200b11f5148eba5899.d",
    ),
    (
        ".dot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        true,
        "dh/~2edot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc7d652aee93f04dd1d4c5ab148404729a76c8d026.i",
        "dh/~2edot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2053154c24f5b4e6074de2d23b1e59d17dc4724e.d",
    ),
    (
        ".dot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        false,
        "dh/.dot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc7d652aee93f04dd1d4c5ab148404729a76c8d026.i",
        "dh/.dot/cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc2053154c24f5b4e6074de2d23b1e59d17dc4724e.d",
    ),
    (
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/f",
        true,
        "dh/aaaaaaaa/bbbbbbbb/f.i3368c89715821b935f6173f4f21ac1235ff74013.i",
        "dh/aaaaaaaa/bbbbbbbb/f.d7199e306b1713a680b4bb8d6d37fe5208869251e.d",
    ),
    (
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/f",
        false,
        "dh/aaaaaaaa/bbbbbbbb/f.i3368c89715821b935f6173f4f21ac1235ff74013.i",
        "dh/aaaaaaaa/bbbbbbbb/f.d7199e306b1713a680b4bb8d6d37fe5208869251e.d",
    ),
    (
        "aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/hhhhhhhh/iiiiiiii/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        true,
        "dh/aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/zzzzzzzzzzzz20f12fe2307ac31000a71f5a6c7406af40feb900.i",
        "dh/aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/zzzzzzzzzzzz663ecd9a37a08184644730f6f52c0401e299edc3.d",
    ),
    (
        "aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/hhhhhhhh/iiiiiiii/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        false,
        "dh/aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/zzzzzzzzzzzz20f12fe2307ac31000a71f5a6c7406af40feb900.i",
        "dh/aaaaaaaa/bbbbbbbb/cccccccc/dddddddd/eeeeeeee/ffffffff/gggggggg/zzzzzzzzzzzz663ecd9a37a08184644730f6f52c0401e299edc3.d",
    ),
    (
        ".....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
        true,
        "dh/~2e....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq360c3a54f4f33aebcc79ad65079edb47a92e1467.i",
        "dh/~2e....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq70e3853c163e20438e7dce5302e220bff4732b80.d",
    ),
    (
        ".....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
        false,
        "dh/.....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq360c3a54f4f33aebcc79ad65079edb47a92e1467.i",
        "dh/.....qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq70e3853c163e20438e7dce5302e220bff4732b80.d",
    ),
    (
        "Dir.i/BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        true,
        "dh/dir.i.hg/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb34044db9498d4b64d0a2a54e999ab7ad8d33e7d6.i",
        "dh/dir.i.hg/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7aa8b3f777c43a3bebf47066412249832da7c9e0.d",
    ),
    (
        "Dir.i/BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        false,
        "dh/dir.i.hg/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb34044db9498d4b64d0a2a54e999ab7ad8d33e7d6.i",
        "dh/dir.i.hg/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7aa8b3f777c43a3bebf47066412249832da7c9e0.d",
    ),
    (
        "x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
        true,
        "dh/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy26b2b9e775a8d2cd3aa1c1927d43f123feeaa2d3.i",
        "dh/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyye5da8099f4b45c4b069970ad56d9992c0a73244e.d",
    ),
    (
        "x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
        false,
        "dh/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy26b2b9e775a8d2cd3aa1c1927d43f123feeaa2d3.i",
        "dh/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/x/com1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyye5da8099f4b45c4b069970ad56d9992c0a73244e.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "dh/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnfe4ae7e2c8c7e76a4348e1985a087cf09abcfa7c.i",
        "dh/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnc57d6e0eea1dc449b71dc63e7334b18c7a80f088.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "dh/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnfe4ae7e2c8c7e76a4348e1985a087cf09abcfa7c.i",
        "dh/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnc57d6e0eea1dc449b71dc63e7334b18c7a80f088.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "data/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "data/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.i",
        "data/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.d",
    ),
    (
        "dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        true,
        "dh/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn8a5f2657c164a16136359a961c19ccb96c8c0e77.i",
        "dh/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbc8c8bcff719e14d5124e1803a2fa13aa6868572.d",
    ),
    (
        "dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
        false,
        "dh/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn8a5f2657c164a16136359a961c19ccb96c8c0e77.i",
        "dh/dd/nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnbc8c8bcff719e14d5124e1803a2fa13aa6868572.d",
    ),
    (
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        true,
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.i9402b6073ca23fe39ee42e19bedd0c4d81a5728d.i",
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.d9e5d86c868b505b14fbf0a806d6bba7db46b3394.d",
    ),
    (
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        false,
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.i9402b6073ca23fe39ee42e19bedd0c4d81a5728d.i",
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.d9e5d86c868b505b14fbf0a806d6bba7db46b3394.d",
    ),
    (
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        true,
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.i9739a3a7d917612dacb7aa74171f78a272fe2751.i",
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.d9b90f99eb37ab19ce78e7ed06862b54e4d936141.d",
    ),
    (
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        false,
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.i9739a3a7d917612dacb7aa74171f78a272fe2751.i",
        "dh/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.d9b90f99eb37ab19ce78e7ed06862b54e4d936141.d",
    ),
];

#[test]
fn every_path_equals_mercurials_own_encoding_for_both_files() {
    assert!(FROM_MERCURIAL.len() > 100);
    for (logical, dotencode, index, data) in FROM_MERCURIAL {
        let got = store_paths(logical, *dotencode).unwrap();
        assert_eq!(
            got,
            StorePaths {
                index: (*index).to_string(),
                data: (*data).to_string(),
            },
            "{logical:?} (dotencode {dotencode})"
        );
    }
}

#[test]
fn the_handoffs_table_of_paths_brygge_used_to_get_wrong() {
    let rows = [
        ("aux/x", "data/au~78/x.i"),
        ("con.txt", "data/co~6e.txt.i"),
        ("com1", "data/co~6d1.i"),
        ("dir.i/f", "data/dir.i.hg/f.i"),
        (".hg/x", "data/~2ehg.hg/x.i"),
        ("a./b", "data/a~2e/b.i"),
        ("a /b", "data/a~20/b.i"),
    ];
    for (logical, want) in rows {
        assert_eq!(store_paths(logical, true).unwrap().index, want, "{logical}");
    }
    // The earlier, reversible cases are unchanged.
    assert_eq!(store_paths("a.txt", true).unwrap().index, "data/a.txt.i");
    assert_eq!(
        store_paths("Sub/File.TXT", true).unwrap().index,
        "data/_sub/_file._t_x_t.i"
    );
    assert_eq!(
        store_paths("_under.txt", true).unwrap().index,
        "data/__under.txt.i"
    );
    assert_eq!(
        store_paths(".hidden", true).unwrap().index,
        "data/~2ehidden.i"
    );
    // Not reserved after the uppercase encoding; and a final component's trailing dot/space is not trailing.
    assert_eq!(
        store_paths("Aux.txt", true).unwrap().index,
        "data/_aux.txt.i"
    );
    assert_eq!(store_paths("x.", true).unwrap().index, "data/x..i");
}

#[test]
fn a_hashed_name_is_named_separately_for_the_index_and_the_data_file() {
    let long = format!("{}file.txt", "director/".repeat(12));
    let p = store_paths(&long, true).unwrap();
    assert!(p.index.starts_with("dh/") && p.data.starts_with("dh/"));
    assert!(p.index.ends_with(".i") && p.data.ends_with(".d"));
    // The SHA-1 of the whole path is in the name, and the paths differ, so the names differ in more than
    // their extension: the `.d` name cannot be derived from the `.i` name.
    assert_ne!(
        p.index.strip_suffix(".i"),
        p.data.strip_suffix(".d"),
        "the two files' names differ before the extension"
    );
    assert!(p.index.len() <= 120 && p.data.len() <= 120);
}

#[test]
fn rejects_bad_paths() {
    for bad in ["", "/abs", "a//b", "a/", "./a", "a/../b", "a/./b", ".."] {
        assert!(store_paths(bad, true).is_err(), "{bad:?}");
    }
}

#[test]
fn a_long_path_is_no_longer_refused() {
    let overlong = format!("{}.txt", "x".repeat(200));
    let p = store_paths(&overlong, true).unwrap();
    assert!(p.index.starts_with("dh/"), "{}", p.index);
}

fn hg_available() -> bool {
    Command::new("hg")
        .arg("--version")
        .env("HGRCPATH", "/dev/null")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

#[test]
fn every_fncache_path_maps_to_an_existing_store_file() {
    if !hg_available() {
        eprintln!("skipping: hg not on PATH");
        return;
    }
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("brygge-hg-fn-{}-{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    struct Clean(PathBuf);
    impl Drop for Clean {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }
    let _c = Clean(dir.clone());
    let hg = |args: &[&str]| {
        let out = Command::new("hg")
            .env("HGRCPATH", "/dev/null")
            .arg("--cwd")
            .arg(&dir)
            .arg("-R")
            .arg(&dir)
            .arg("--config")
            .arg("ui.username=A <a@e.com>")
            .args(args)
            .output()
            .expect("hg");
        assert!(
            out.status.success(),
            "hg {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    };
    hg(&["init", dir.to_str().unwrap()]);
    for name in [
        "a.txt",
        "Sub/File.TXT",
        "_under.txt",
        ".hidden",
        ".config/App.ini",
        "MixedCase.md",
    ] {
        let p = dir.join(name);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::write(&p, b"x\n").unwrap();
    }
    hg(&["add"]);
    hg(&["commit", "-d", "1 0", "-m", "c0"]);
    let fncache = std::fs::read_to_string(dir.join(".hg/store/fncache")).unwrap();
    for line in fncache.lines().filter(|l| !l.trim().is_empty()) {
        // fncache entries look like "data/<logical>.i"
        let logical = line
            .strip_prefix("data/")
            .and_then(|s| s.strip_suffix(".i"))
            .unwrap_or_else(|| panic!("unexpected fncache entry {line:?}"));
        let encoded = store_paths(logical, true)
            .expect("encode fncache path")
            .index;
        assert!(
            dir.join(".hg/store").join(&encoded).exists(),
            "logical {logical:?} -> {encoded:?} does not exist on disk"
        );
    }
}
